

server:
  port: 8081
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
  datasource:
    url : jdbc:mysql://localhost:3306/bapp?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username : root
    password : qiuhen
    driverClassName : com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update   #自动更新
    show-sql: true       #日志中显示sql



logging:
  # 配置输出额日志文件名,可以带路径
  #  file: out.log
  # 配置日志存放路径,日志文件名为：spring.log
  path: ./log                    #path与file同时存在path失效
  file:
    # 设置日志文件大小
    max-size: 10MB
  level:
    # root日志以WARN级别输出
    root: info
    # 此包下所有class以DEBUG级别输出
    com.qiuhen.bapp.pojo: warn

